package com.teqamaze.laundry.error;

public enum LaundryError {

    TSL_ERROR_LAUNDRY_USER_ID_INVALID(10000, "TLS-ERROR-LAUNDRY-USER-ID-INVALID"),
    TSL_ERROR_LAUNDRY_USER_EMAIL_INVALID(10001, "TLS-ERROR-LAUNDRY-VENDOR-ID-INVALID"),
    TSL_ERROR_LAUNDRY_VENDOR_ID_INVALID(10002, "TLS-ERROR-LAUNDRY-USER-ID-INVALID"),
    TSL_ERROR_LAUNDRY_VENDOR_EMAIL_INVALID(10003, "TLS-ERROR-LAUNDRY-VENDOR-EMAIL-INVALID"),
    TSL_ERROR_LAUNDRY_NULL_OTP(10004, "TLS-ERROR-LAUNDRY-PLEASE-PROVIDE-OTP"),
    TSL_ERROR_LAUNDRY_INVALID_OTP(10005, "TLS-ERROR-LAUNDRY-PLEASE-PROVIDE-GENUINE OTP"),
    TSL_ERROR_LAUNDRY_EXPIRED_OTP(10006, "TLS-ERROR-LAUNDRY-OTP-HAS-EXPIRED"),
    TSL_ERROR_LAUNDRY_SOMETHING_WRONG(10007, "TLS-ERROR-LAUNDRY-SOMETHING-WENT-WRONG"),
    TSL_ERROR_LAUNDRY_NUMBER_NOT_FOUND(10008, "TLS-ERROR-LAUNDRY-OTP-HAS-EXPIRED"),
    TSL_ERROR_LAUNDRY_NUMBER_INVALID(10009, "TLS-ERROR-LAUNDRY-NUMBER-INVALID"),
    TSL_ERROR_LAUNDRY_USER_NOT_FOUND(10010, "TLS-ERROR-LAUNDRY-USER-NOT-FOUND"),
    TSL_ERROR_LAUNDRY_VENDOR_ALREADY_EXIST(10011, "TSL-ERROR-LAUNDRY-VENDOR-ALREADY-EXIST"),
    TSL_ERROR_LAUNDRY_VENDOR_DOES_NOT_EXIST(10012, "TSL-ERROR-LAUNDRY-VENDOR-DOES-NOT-EXIST"),
    TSL_ERROR_LAUNDRY_INVALID_VENDOR_CODE(10013, "TSL-ERROR-LAUNDRY-INVALID-VENDOR-CODE"),
    TSL_ERROR_LAUNDRY_ORDER_ID_INVALID(10014, "TLS-ERROR-LAUNDRY-ORDER-ID-INVALID"),
    TSL_ERROR_LAUNDRY_ORDER_NOT_FOUND(10015, "TLS-ERROR-LAUNDRY-THERE-IS-NO-ORDER"),
    TSL_ERROR_LAUNDRY_NO_ORDER_FOR_THIS_USER_ID(10016, "TLS-ERROR-LAUNDRY-NO-ORDER-AVAILABLE-FOR-THIS-USER"),
    TSL_ERROR_LAUNDRY_NO_ORDER_FOR_THIS_VENDOR_ID(10017, "TLS-ERROR-LAUNDRY-NO-ORDER-FOR-THIS-VENDOR"),
    TSL_ERROR_LAUNDRY_UPDATE_ORDER_FAILED(10018, "TLS-ERROR-LAUNDRY-UPDATE_ORDER_FAILED."),
    TSL_ERROR_LAUNDRY_VENDOR_NOT_FOUND(10019, "TLS-ERROR-LAUNDRY-THERE-IS-NO-VENDOR");
    
    
    /**
     * @param errorCode
     * @param errorKey
     */
    private LaundryError(int errorCode, String errorKey) {
        this.errorCode = errorCode;
        this.errorKey = errorKey;
    }
    

    private LaundryError() {
    }


    private int errorCode;

    private String errorKey;

    public int getErrorCode() {
        return errorCode;
    }

    public String getErrorKey() {
        return errorKey;
    }
    
    @Override
    public String toString() {
        return this.errorCode + " : " + this.errorKey;
    }
}
